---

# Head plugin
- include: plugins/head.yml
  when: es_install_head is defined and es_install_head

# Marvel plugin
- include: plugins/marvel.yml
  when: es_install_marvel is defined and es_install_marvel

# Kopf plugin
- include: plugins/kopf.yml
  when: es_install_kopf is defined and es_install_kopf

# ElasticHQ plugin
- include: plugins/elastichq.yml
  when: es_install_eshq is defined and es_install_eshq

# Curator tool
- include: plugins/curator.yml
  when: es_install_curator is defined and es_install_curator

# cloud-aws tool
- include: plugins/cloud-aws.yml
  when: es_install_cloudaws is defined and es_install_cloudaws
